# Generated by Django 4.0.6 on 2022-08-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='imagen',
        ),
        migrations.AddField(
            model_name='terreno',
            name='mapa',
            field=models.URLField(blank=True, help_text='https://www.google.com/maps/embed/v1/place?key=AIzaSyD1z4IMQxdXYu9060zvOdbViL233dT-IxI&q=', null=True),
        ),
    ]
