# Generated by Django 4.0.6 on 2022-08-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0002_remove_terreno_imagen_terreno_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
