# Generated by Django 4.0.6 on 2022-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0003_alter_terreno_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='descripcion_corta',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
