# Generated by Django 4.0.6 on 2022-08-12 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Departamento', max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=10000, null=True)),
                ('ambientes', models.IntegerField(default=2)),
                ('cochera', models.BooleanField(default=False)),
                ('en_alquiler', models.BooleanField(default=True)),
                ('en_venta', models.BooleanField(default=False)),
                ('precio', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades')),
                ('mapa', models.URLField(blank=True, help_text='https://www.google.com/maps/embed/v1/place?key=AIzaSyD1z4IMQxdXYu9060zvOdbViL233dT-IxI&q=', null=True)),
            ],
        ),
    ]
