# Generated by Django 4.0.6 on 2022-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_descripcion_corta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion_corta',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
