# Generated by Django 4.0.6 on 2022-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_alter_propiedad_descripcion_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='baños',
            field=models.IntegerField(default=1),
        ),
    ]
