# Generated by Django 4.0.6 on 2022-09-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_propiedad_baños'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='mapa',
            field=models.URLField(blank=True, help_text='https://www.google.com/maps/embed/v1/place?key=APIKEY-IxI&q=', null=True),
        ),
    ]
